### ISSUE TITLE
Error when trying to run the gui

### ISSUE THREAD

**Issue by Golecom** [johnfanv2/LenovoLegionLinux#160]
Hello, im trying to run the gui like the guide says but im getting this error:

gonzalo@Legion5Pro:~/LenovoLegionLinux$ sudo python/legion_linux/legion_linux/legion_gui.py
Traceback (most recent call last):
  File "/home/gonzalo/LenovoLegionLinux/python/legion_linux/legion_linux/legion_gui.py", line 12, in <module>
    from PyQt5 import QtGui, QtCore
ModuleNotFoundError: No module named 'PyQt5'

I'm runnig Nobara 39

thanks

**Comment by Golecom** [comment]
If i run the the legion_gui.py from dolphin, the gui opens but there is a message that it needs to run as root.

**Comment by Codyport** [comment]
I had to do a 
`sudo apt install python3-pyqt6`

**Comment by selfhostit** [comment]
I already have it installed, but I'm getting the same error. The app was working just fine like 2 weeks ago.

**Comment by MrDuartePT** [comment]
I notice that the package for Fedora sometimes have a bug, and for some reason doesn't install `PyQT6`.
I gonna create new packages today, and since `PyQT6` is on the dependencies: 
https://github.com/johnfanv2/LenovoLegionLinux/blob/472dddeb72689c45930835a10ee20a0d4be5be55/deploy/build_packages/lenovolegionlinux.spec#L23C1-L23C20

Should get solved!
