### ISSUE TITLE
What is the expected behavior of mini fan curve when `/sys/module/legion_laptop/drivers/platform:legion/.../minifancurve` is set to `0` and `1` respectively?

### ISSUE THREAD

**Issue by BellaCoola** [johnfanv2/LenovoLegionLinux#175]
Hello, I am running LenovoLegionLinux on Lenovo Legion 5 Pro 16ITH6H. I was experimenting a bit with setting `/sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/hwmon/hwmon3/minifancurve` to both `0` and `1`. These are my observations:

- When set to `0`, the `EC fan curve points size` entry in `/sys/kernel/debug/legion/fancurve` reports `4` all the time. (I.e. it seems as if the mini fan curve was enabled all the time.)
- When set to `1`, the `EC fan curve points size` entry in `/sys/kernel/debug/legion/fancurve` changes from `4` to `9` depending on load. (I.e. it seems as if the mini fan curve was enabled or disabled based on load.)

Please, is this an expected behavior?
Also, is it somehow possible to completely disable the mini fan curve? (Make the `EC fan curve points size` entry in `/sys/kernel/debug/legion/fancurve` report `9` all the time?)

Thank you very much and have a nice day :slightly_smiling_face:

**Comment by MrDuartePT** [comment]
It explain on the README how the minifancurve works: https://github.com/johnfanv2/LenovoLegionLinux#enable-or-disable-the-mini-fan-curve

You probably experience that behavior since you didnt power profile cycle the EC after disable the minifancurve. 
When minifancurve is disable the EC requires to change power profile to get 9 points available again.

Also when `/sys/module/legion_laptop/drivers/platform:legion/PNP0C09:00/hwmon/hwmon3/minifancurve` is set to `0` the minifancurve is always disable also exist `legion_cli` commands to enable, disable and check the status of minifancurve. Also the gui have a toogle to disable.

If you answer get resolve, pls close this issue.
Have a nice day😁

**Comment by st0nie** [comment]
It's been a long time since we've made any progress on this issue, so let's close it for now
