### ISSUE TITLE
windows support 

### ISSUE THREAD

**Issue by marwan4mr** [johnfanv2/LenovoLegionLinux#25]
I would honestly love to see this tool on windows, I know the tools available for windows, but this offers something that others don't, would you consider making a version for windows?

**Comment by johnfanv2** [comment]
Unfortunately, it will not be compatible with Windows. Its is programmed to be tightly coupled with Linux because I want to integrate it into the Linux kernel.

**Comment by russellmm** [comment]
This is a real bummer. I just bought the Legion Slim 7 (AMD/4060) and the way Lenovo handles the fan control on their Legion laptops is horrid. LegionFanControl is no longer supported (does not work on 2023 model) and LFC only uses exposed API and does not write to the EC.
Will be returning an otherwise greatr laptop and sticking with my ASUS G14.
